# Generated by Django 4.1.1 on 2022-10-25 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseTrait',
            fields=[
                ('Disease_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('Pubmedid', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('Journal', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=1000, unique=True)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SNP',
            fields=[
                ('Rsid', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Chrom', models.CharField(max_length=100)),
                ('Chrom_pos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pvalue', models.FloatField()),
                ('Neglog10pvalue', models.FloatField()),
                ('Disease_trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SNP_App.diseasetrait')),
                ('Reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SNP_App.reference')),
                ('SNP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SNP_App.snp')),
            ],
        ),
    ]
