# Generated by Django 4.1.1 on 2022-10-01 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pubmedid', models.PositiveIntegerField()),
                ('Journal', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=1000)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SNP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chrom', models.CharField(max_length=100)),
                ('Chrom_pos', models.PositiveIntegerField()),
                ('Rsid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SNP2Phenotype2Ref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pvalue', models.FloatField()),
                ('Neglog10pvalue', models.FloatField()),
                ('Disease_trait_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SNP_App.diseasetrait')),
                ('Reference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SNP_App.reference')),
                ('SNP_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SNP_App.snp')),
            ],
        ),
    ]
