# Generated by Django 4.1.1 on 2022-10-01 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SNP_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snp2phenotype2ref',
            old_name='Disease_trait_id',
            new_name='Disease_trait',
        ),
        migrations.RenameField(
            model_name='snp2phenotype2ref',
            old_name='Reference_id',
            new_name='Reference',
        ),
        migrations.RenameField(
            model_name='snp2phenotype2ref',
            old_name='SNP_id',
            new_name='SNP',
        ),
    ]
