# Generated by Django 4.1.1 on 2022-10-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SNP_App', '0002_rename_disease_trait_id_snp2phenotype2ref_disease_trait_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SNP2Phenotype2Ref',
            new_name='Association',
        ),
    ]
